#cloud-config
users:
  - name: ${username}
    shell: /bin/bash
    lock_passwd: false
    ssh_authorized_keys:
      - ${public_key}
    sudo: ALL=(ALL) NOPASSWD:ALL
package_update: true
packages:
  - wireguard
write_files:
  - content: |
      ${config}
    path: /etc/wireguard/wg0.conf
    permissions: '0600'
runcmd:
  - systemctl enable --now wg-quick@wg0
  - echo "net.ipv4.ip_forward=1" >/etc/sysctl.d/00-ip-forwarding.conf
  - sysctl -p /etc/sysctl.d/00-ip-forwarding.conf
  - ufw allow 51820/udp
